steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/our-bebop-457813-a2/convomatefrontend', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/our-bebop-457813-a2/convomatefrontend']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'convomatefrontend'
      - '--image'
      - 'gcr.io/our-bebop-457813-a2/convomatefrontend'
      - '--platform'
      - 'managed'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/our-bebop-457813-a2/convomatefrontend'

timeout: '1800s'  # 30 minutes timeout 